In [2]:
#numpy : 배열의 연산등을 쉽게 처리할 수 있게 

import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
print(a,type(a))
print("----------------")
print(a.ndim,a.shape, a.size, a.dtype,a.dtype.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] <class 'numpy.ndarray'>
----------------
2 (3, 5) 15 int32 4


In [4]:
np.arange(-10,5,0.5)          #numpy에 있는 arange를 사용.
#np.arange(-10,5,0.5).size    #np.arange(-10,5,0.5) 의 사이즈가 나온다.

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5])

In [5]:
np.arange(-10,5,0.5).reshape(5,6)               #5행 6열로 만들어줌 
                                                #대괄호로 묶인 데이터를 따로 불러다 사용 가능? 그렇다면 열도?

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5],
       [ -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5],
       [ -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5,   4. ,   4.5]])

In [6]:
a_list = [1,2,3,4,5,6]
a_array = np.array(a_list)
print(type(a_list),type(a_array),a_list,a_array)
a_array.shape

<class 'list'> <class 'numpy.ndarray'> [1, 2, 3, 4, 5, 6] [1 2 3 4 5 6]


(6,)

In [7]:
#Inf, Nan, 초기값 설정한 배열 생성
a = np.zeros(5)
b = np.ones((2,3,4), dtype='U4')
print(a,"\n","\n","\n",b)

[0. 0. 0. 0. 0.] 
 
 
 [[['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]]


In [10]:
#array 연산

x1 = np.array([1,2,3])
y1 = np.array([4,5,6])
x2 = np.array([[1,2],[3,4]])
z1 = np.array([-1,-2])


print(x1+y1)
print(x2+z1)
print(x2.flatten())
print(x1.reshape(2,2)) #reshape은 배열을 다시 재배치


[5 7 9]
[[0 0]
 [2 2]]
[1 2 3 4]


ValueError: cannot reshape array of size 3 into shape (2,2)

In [12]:
#indexing, slicing, iterating

a = np.arange(10)**2
print(a)
print(a[2])   #0 index부터 시작, 4
print(a[3:5]) # 9, 16 => 시작은 포함 끝은 미포함
print(-a[0:6:2])  # [start : end : step]
a[0 : 6 : 2] = -a[0 : 6 : 2]
print(a[0:6:2])
a[ : : -1]   #reverse a


b = a.reshape(2,5)
print(b)
print(b[:,-1])
print(b[-1,-1])

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16]
[  0  -4 -16]
[  0  -4 -16]
[[  0   1  -4   9 -16]
 [ 25  36  49  64  81]]
[-16  81]
81


In [13]:
import numpy as np

a = np.array([[2,3,4],[4,5,6],[7,8,9]])
print(np.max(a, axis=1))              #axis = 0 (행), 1 (열)

[4 6 9]


In [15]:
print(np.mean(a[0]),np.var(a),np.median(a), len(a), a.size)

3.0 4.888888888888889 5.0 3 9


In [36]:
np.random.seed(100)          #seed로 고정
np.random.rand(5)            #랜덤 돌려도 동일한 값 도출

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [37]:
np.random.choice(5,3, replace = False)

array([3, 0, 4])

In [48]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(x[x%3 == 0])                 #배열에서 3의배수 찾기
print(x[x%4 == 1])                 #배열에서 4로 나눌 때 1이 남는 수
a1= x[[x%3 == 0]]
a2= a1[[a1%4 == 1]]
   
print(x[(x%3==0) & (x%4==1)])       #패키지마다 지원되는게 달라서 and가 안될 수가 있음    & : and, |: or 
print(a2)                           #배열에서 3으로 나눠지면서 4로 나눴을 때 나머지가 1인 수

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
[9]


<ipython-input-48-325c3e180993>:4: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a1= x[[x%3 == 0]]
<ipython-input-48-325c3e180993>:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  a2= a1[[a1%4 == 1]]


In [68]:
#1부터 100까지의 숫자들 중에서 3의 배수만 배열로 생성
a= np.arange(101)
x1 = a[1:]
x2 = x1.reshape(10,10)
print("1에서 100까지의 수","\n",x2)
print("-----------------------------","\n","-----------------------------")
print("1에서 100까지 중 3의 배수인 수:","\n",x2[x2 % 3 == 0])

1에서 100까지의 수 
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
----------------------------- 
 -----------------------------
1에서 100까지 중 3의 배수인 수: 
 [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [76]:
arr = np.arange(1,101)
arr = arr[arr % 3 == 0]
print("arr:", arr)

#위에서 생성된 배열의 값 중에서 임의로 5개의 값을 출력
print("임의의 수 5개를 출력:",np.random.choice(arr, 5, replace = False))         #replace : 중복해서 쓰지 않기 위해 
#위의 배열의 사이즈를 확인한 후 행이 3인 2차원 배열을 생성
arr_1 = arr.reshape(3,int(arr.size/3))
#배열의 원소중에서 5의 배수만 출력
print("5의 배수만 출력: ",arr_1[arr_1%5 ==0])

arr: [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
임의의 수 5개를 출력: [96 87 15 69 21]
5의 배수만 출력:  [15 30 45 60 75 90]
